/* eslint-disable react/jsx-props-no-spreading */
import { ThemeProvider } from '@/frontend/components/context'
import WithNavigation from '@/frontend/components/layouts/WithNavigation/WithNavigation'
import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { appWithTranslation } from 'next-i18next'

function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>dobleB. by Boris Belmar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider>
        <main className="text-dark-primary-700 dark:text-primary-50">
          <WithNavigation>
            <Component {...pageProps} />
          </WithNavigation>
        </main>
      </ThemeProvider>
    </>
  )
}

export default appWithTranslation(App)
