import { Article } from '@/frontend/@types/Article'
import { Project } from '@/frontend/@types/Project'
import { HomeScreen } from '@/frontend/components/screens'
import articlesMock from '@/frontend/mocks/articles'
import projectsMock from '@/frontend/mocks/projects'
import Head from 'next/head'

export const getServerSideProps = async () => {
  return {
    props: {
      projects: [...projectsMock].splice(0, 4),
      articles: [...articlesMock].splice(0, 3)
    }
  }
}

interface Props {
  projects: Project[]
  articles: Article[]
}

export default function Home({
  projects,
  articles
}: Props) {
  return (
    <>
      <Head>
        <title>dobleB. by Boris Belmar</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomeScreen
        projects={projects}
        articles={articles}
      />
    </>
  )
}
