import { Article } from '@/frontend/@types/Article'
import { Project } from '@/frontend/@types/Project'
import { HomeScreen } from '@/frontend/components/screens'
import { getFeaturedArticles } from '@/frontend/services/articles'
import { getFeaturedProjects } from '@/frontend/services/projects'
import Head from 'next/head'

export const getServerSideProps = async () => {
  const [projects, articles] = await Promise.all([
    getFeaturedProjects(),
    getFeaturedArticles()
  ])

  return {
    props: {
      projects,
      articles
    }
  }
}

interface Props {
  projects: Project[]
  articles: Article[]
}

export default function Home({
  projects,
  articles
}: Props) {
  return (
    <>
      <Head>
        <title>dobleB. by Boris Belmar</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomeScreen
        projects={projects}
        articles={articles}
      />
    </>
  )
}
